-- Bridge Group — PostgreSQL setup (database + schema in one file)
--
-- Run from your terminal (no password needed on your machine):
--   psql -U postgres -f bridge_groups.sql
-- or, if that is refused:
--   sudo -u postgres psql -f bridge_groups.sql
--
-- Safe to run more than once: nothing is dropped, everything is "if not exists".

\set ON_ERROR_STOP on

-- ---------------------------------------------------------------------------
-- 1. Create the database (only if it does not exist yet)
-- ---------------------------------------------------------------------------
SELECT 'CREATE DATABASE bridge_groups'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'bridge_groups')
\gexec

\connect bridge_groups

BEGIN;

-- ---------------------------------------------------------------------------
-- 2. Enum types
-- ---------------------------------------------------------------------------
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'user_role') THEN
    CREATE TYPE user_role AS ENUM ('innovator', 'investor', 'admin');
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'project_stage') THEN
    CREATE TYPE project_stage AS ENUM ('concept', 'prototype', 'early_revenue', 'scaling', 'approved');
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'project_status') THEN
    CREATE TYPE project_status AS ENUM ('pending', 'approved', 'rejected', 'live');
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'milestone_status') THEN
    CREATE TYPE milestone_status AS ENUM ('pending', 'in_progress', 'completed');
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'investment_status') THEN
    CREATE TYPE investment_status AS ENUM ('pending', 'active', 'completed');
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'transaction_type') THEN
    CREATE TYPE transaction_type AS ENUM ('return', 'revenue_share', 'valuation_update');
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'ledger_direction') THEN
    CREATE TYPE ledger_direction AS ENUM ('inflow', 'outflow');
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'idea_status') THEN
    CREATE TYPE idea_status AS ENUM (
      'submitted',
      'under_review',
      'department_review',
      'approved',
      'rejected'
    );
  END IF;
END
$$;

-- ---------------------------------------------------------------------------
-- 3. Tables
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name         text        NOT NULL,
  email             text        NOT NULL UNIQUE,
  password_hash     text        NOT NULL,
  role              user_role   NOT NULL,
  company           text,
  bio               text,
  avatar_url        text,
  expertise_fields  text[]      NOT NULL DEFAULT '{}',
  created_at        timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS users_email_lower_unique_idx ON users (lower(email));

CREATE TABLE IF NOT EXISTS password_reset_tokens (
  token_hash     text        PRIMARY KEY,
  user_id        bigint      NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  expires_at     timestamptz NOT NULL,
  used_at        timestamptz,
  created_at     timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS categories (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name           text        NOT NULL UNIQUE,
  slug           text        NOT NULL UNIQUE,
  description    text        NOT NULL DEFAULT '',
  icon           text,
  color          text,
  project_count  integer     NOT NULL DEFAULT 0,
  created_at     timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS projects (
  id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title              text        NOT NULL,
  category           text        NOT NULL,
  category_id        bigint      REFERENCES categories(id) ON DELETE SET NULL,
  description        text        NOT NULL,
  problem            text        NOT NULL,
  solution           text        NOT NULL,
  stage              text        NOT NULL,
  funding_goal       numeric     NOT NULL,
  funding_raised     numeric     NOT NULL DEFAULT 0,
  equity_offered     numeric     NOT NULL DEFAULT 0,
  revenue_share_pct  numeric     NOT NULL DEFAULT 0,
  roi_projection     numeric,
  status             text        NOT NULL DEFAULT 'live',
  image_url          text,
  innovator_id       bigint      NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  created_at         timestamptz NOT NULL DEFAULT now(),
  updated_at         timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS milestones (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id    bigint           NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  title         text             NOT NULL,
  description   text             NOT NULL DEFAULT '',
  target_date   date,
  completed_at  timestamptz,
  status        milestone_status NOT NULL DEFAULT 'pending',
  created_at    timestamptz      NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS investments (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  investor_id  bigint      NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  project_id   bigint      NOT NULL REFERENCES projects(id) ON DELETE RESTRICT,
  amount       numeric     NOT NULL,
  equity_pct   numeric     NOT NULL DEFAULT 0,
  status       text        NOT NULL DEFAULT 'active',
  created_at   timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS transactions (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  investment_id  bigint      NOT NULL REFERENCES investments(id) ON DELETE CASCADE,
  project_title  text        NOT NULL,
  amount         numeric     NOT NULL,
  type           text        NOT NULL,
  description    text        NOT NULL,
  created_at     timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS financial_ledger (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id        bigint           NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  project_id     bigint           REFERENCES projects(id) ON DELETE SET NULL,
  category       text             NOT NULL,
  direction      ledger_direction NOT NULL,
  amount         numeric          NOT NULL,
  balance_after  numeric          NOT NULL,
  status         text             NOT NULL DEFAULT 'posted',
  description    text             NOT NULL,
  created_at     timestamptz      NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS payouts (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     bigint      NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  project_id  bigint      REFERENCES projects(id) ON DELETE SET NULL,
  amount      numeric     NOT NULL,
  status      text        NOT NULL DEFAULT 'pending',
  type        text        NOT NULL DEFAULT 'distribution',
  created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS messages (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sender_id    bigint      NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  receiver_id  bigint      NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  project_id   bigint      REFERENCES projects(id) ON DELETE SET NULL,
  content      text        NOT NULL,
  read_at      timestamptz,
  created_at   timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT messages_not_self CHECK (sender_id <> receiver_id)
);

CREATE TABLE IF NOT EXISTS community_posts (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category     text        NOT NULL,
  author_id    bigint      NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  author_name  text        NOT NULL,
  author_role  text        NOT NULL,
  title        text        NOT NULL,
  content      text        NOT NULL,
  replies      integer     NOT NULL DEFAULT 0,
  created_at   timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS idea_requests (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  innovator_id    bigint      NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  title           text        NOT NULL,
  category        text        NOT NULL,
  field           text        NOT NULL,
  problem         text        NOT NULL,
  solution        text        NOT NULL,
  pitch           text        NOT NULL,
  founder_name    text        NOT NULL,
  email           text        NOT NULL,
  status          text        NOT NULL DEFAULT 'submitted',
  score           integer     DEFAULT 0,
  department      text,
  review_summary  text,
  admin_notes     text,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS project_follows (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  investor_id  bigint      NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  project_id   bigint      NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  created_at   timestamptz NOT NULL DEFAULT now(),
  UNIQUE (investor_id, project_id)
);

-- ---------------------------------------------------------------------------
-- 4. Indexes
-- ---------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_projects_innovator       ON projects (innovator_id);
CREATE INDEX IF NOT EXISTS idx_projects_status          ON projects (status);
CREATE INDEX IF NOT EXISTS idx_investments_investor     ON investments (investor_id);
CREATE INDEX IF NOT EXISTS idx_investments_project      ON investments (project_id);
CREATE INDEX IF NOT EXISTS idx_ledger_user              ON financial_ledger (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_messages_participants    ON messages (sender_id, receiver_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_ideas_innovator          ON idea_requests (innovator_id);
CREATE INDEX IF NOT EXISTS idx_community_posts_category ON community_posts (category);

-- ---------------------------------------------------------------------------
-- 5. updated_at triggers
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_projects_updated_at ON projects;
CREATE TRIGGER trg_projects_updated_at
BEFORE UPDATE ON projects
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_ideas_updated_at ON idea_requests;
CREATE TRIGGER trg_ideas_updated_at
BEFORE UPDATE ON idea_requests
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

COMMIT;
